### ISSUE TITLE
flaky usdt test

### ISSUE THREAD

**Issue by xh4n3** [bpftrace/bpftrace#2402]
### What reproduces the bug?
Trigger CI on the master branch.
https://github.com/iovisor/bpftrace/actions/runs/3343605763/jobs/5536998903
https://github.com/iovisor/bpftrace/actions/runs/3341593002/jobs/5532960039

```bash
2: [ RUN      ] usdt."usdt probes - file based semaphore activation multi process"
2: [  TIMEOUT ] usdt."usdt probes - file based semaphore activation multi process"
2: 	Command: ../src//bpftrace runtime/scripts/usdt_file_activation_multiprocess.bt --usdt-file-activation
2: 	Timeout: 5
2: 	Current output: Attaching 3 probes...
2: __BPFTRACE_NOTIFY_PROBES_ATTACHED
2: found 1 processes
```

**Comment by BurntBrunch** [comment]
I'm fighting with it in https://github.com/iovisor/bpftrace/pull/2370/commits/4eb280b07ee683f62176e06bdbb594c146a72379 but I can't make it stable yet. Now the pidof invocation to get the child pid after it has started is failing. I may just make that logic only run if the test needs BEFORE_PID.

**Comment by viktormalik** [comment]
I think that this should be resolved by #2370

**Comment by BurntBrunch** [comment]
Unfortunately, I don't think it was fully fixed, just made a bit better. I still don't fully understand how this happens (and why it happens on _that_ test specifically) but here's a run after that PR that timed out again - https://github.com/BurntBrunch/bpftrace/actions/runs/3381817256/jobs/5616467787

**Comment by BurntBrunch** [comment]
Okay, I give up.  #2414 doesn't help either, so this is not about the test runner racing the BEFORE calls. Maybe it's something to do with --usdt-file-activation and whatever kernel the GH runners run?

**Comment by jordalgo** [comment]
I don't see this anymore - perhaps @danobi fixed it. Closing for now.
